### ISSUE TITLE
EOS-80 is now obsolete, need to change the package used for seawater property equations

### ISSUE THREAD

**Issue by cgrdn** [ArgoCanada/BGC-QC#17]
The [seawater](https://pypi.org/project/seawater/) package uses EOS-80 equations, which as now considered obsolete. Should transition to [TEOS-10](http://www.teos-10.org/), and use the `gsw` package. In my experience this can be a bit of a fight to install because it uses/relies on C++ on the backend, so could to a soft warning and opt for `seawater` if `gsw` isn't installed. Would work similarly to how `cmocean` or  `seaborn` imports are handled.

**Comment by cgrdn** [comment]
Made change in commit 875b19d, still allows seawater. Code chuck: 

```python
# soft attempt to load gsw, but allow for seawater as well
try: 
    from gsw import pot_rho_t_exact as pden
except:
    try:
        # if this also fails, just load gsw to throw the error
        from seawater import pden
        warnings.warn('gsw package for thermodynamic equations of seawater not installed, attempting to load seawater package, however seawater uses EOS-80 which is deprecated in favor of TEOS-10, used in gsw-python, see https://teos-10.github.io/GSW-Python/\n')
    except:
        from gsw import pot_rho_t_exact as pden
```

**Comment by richardsc** [comment]
Just a comment, but it isn't really that the EOS-80 *equations* are obsolete, just that the old seawater package is. The EOS-80 equations are still used in the `gsw` package, and still form the basis on which the TEOS-10 equations are built (e.g. floats all still measure Practical Salinity, which is only converted to Absolute Salinity through a calculation that involves latitude and longitude, etc).

Anyway, just is just a caution to say that while the "new" way is supposed to be the default, it isn't always appropriate to use SA/CT in place of SP/PT. The density functions should all be *very* close, though.

**Comment by cgrdn** [comment]
Thanks @richardsc I'll change the warning to reflect that, I misread the explanation on the seawater page about what is deprecated. I was a little hesitant looking at the `gsw` function in terms of matching what the seawater package was doing/proper inputs. Should I be calculating SA before using `pot_rho_t_exact()`? The docstring for it is here: 

```
Signature: gsw.pot_rho_t_exact(SA, t, p, p_ref)
Docstring:
Calculates potential density of seawater.  Note. This function outputs
potential density, not potential density anomaly; that is, 1000 kg/m^3
is not subtracted.

Parameters
----------
SA : array-like
    Absolute Salinity, g/kg
t : array-like
    In-situ temperature (ITS-90), degrees C
p : array-like
    Sea pressure (absolute pressure minus 10.1325 dbar), dbar
p_ref : array-like
    Reference pressure, dbar

Returns
-------
pot_rho_t_exact : array-like, kg/m^3
    potential density (not potential density anomaly)
File:      c:\programdata\anaconda3\lib\site-packages\gsw\_wrapped_ufuncs.py
Type:      function
```

**Comment by richardsc** [comment]
Yes, most of the GSW functions, e.g. for density, will take the Absolute Salinity (rather than Practical), so you need to be careful about just switching one for the other, as you'll first have to pass the float t, S, p, and lon/lat through functions like `gsw_SA_from_SP`.

Happy to talk you through it more if you need it.

**Comment by cgrdn** [comment]
Sounds good, I'm going to re-open the issue to make sure I don't forget to fix it. Will probably message you some questions, thanks!

**Comment by cgrdn** [comment]
If using gsw, now calculate SA from SP with lat/long. If using seawater, don't need to. Code here, committed in 033de72. Closing issue.

```python
# potential density
if flagSA:
    self.PDEN = gsw.pot_rho_t_exact(gsw.SA_from_SP(self.PSAL, self.PRES, self.LONGITUDE_GRID, self.LATITUDE_GRID), self.TEMP, self.LONGITUDE_GRID, self.LATITUDE_GRID) - 1000
else:
    self.PDEN = pden(self.PSAL, self.TEMP, self.PRES, 0) - 1000
```
